var Twit = require('twit')
var config = require('./config')
var T = new Twit(config)

var quotes = [
  "'No thank you' is what I should've said I should be in bed",
  "(Boy, oh boy I love it when I fall for that) No thank you",
  "(Bre-bre-bre) breaking my heart And now you, now you can't go breaking",
  "(But I'm weak)",
  "(Can't no one stop me) (Keep on bouncin')",
  "(Everybody's talking, Everybody's talking)",
  "(forgot what you like) And come hang out don’t you leave us behind",
  "(Hey) We're feeling dumb with coke and rum, we raise a glass to it",
  "(I can't stop and let you go Baby, I gotta mind to let you know)",
  "(I'm gonna buy you a rose Yeah) Tell me my love, you're ready to go?",
  "(I'm gonna buy you a rose Yeah) When I grow up I'll buy you a rose",
  "(It's on us, it's on us) We know what we need to do",
  "(My oh my) And now you can't go breaking my heart, yeah (Right all right) Woah-waa-ooh",
  "(My oh my) And now you can't go breaking my heart, yeah (Right all right) Woah",
  "(No-no grass today) Keep- keep doing keep doing me",
  "(No, it's on us) It's not your fault you don't feel safe",
  "(No, it's on us) We can try together",
  "(Now we're livin' on love) You said marriage has a nice ring to it",
  "(One last chance to make it real Baby, I wanna tell you how I feel)",
  "(Ooh waaaaaaa ee ya ee ya) (Ooh waaaaaaa ee ya ee ya)",
  "(Right all right) To the beginning (Why oh why) What you denied from the start",
  "(Why oh why) And now you can't go breaking my heart (H-heart h-heart)",
  "(Why oh why) And now you can't go breaking my heart The world is a marble heart;",
  "(Why oh why) And now you can't go breaking my heart",
  "(Yeah, take my, take my heart) Take me to your special place",
  "(yodeling) (We so thirsty)",
  "(yodeling) Thirsty thirsty thursday",
  "1-2-3-4 (so can we skip to the good part?) Ah (to the good part, to the good part)",
  "1-2-3-4 Ah (woo)",
  "1-2-3-4 Ah",
  "1-2-3-4 Have I done my best here or",
  "1-2-3-4 If there's a good part then",
  "A heartbreak and a hundred red balloons, now I'm off the floor So here I go",
  "A people person in a room of people-people Imma be the kid for the win",
  "A year from now, we won't be pretty A year from now, we won't be young",
  "About the old days, gold days, how we've been The city's rusty after what we did, we did, we did, we did",
  "Across the floor, and I'm already losing my mind Baby girl, looking fine",
  "After the party's done And all is well",
  "Ah Ah",
  "All I want is you, my dear We will live up on the tree",
  "All my new friends We smile at party time",
  "All of my life I have been starving Not for a dinner with friends, more of a starving artist",
  "All our troubles gone Like when we were young",
  "All the big kids, they got drunk And I want to feel something again",
  "Am I ready for love? Or maybe just a best friend",
  "And all is well But I'm scared as hell",
  "And all my friends say Come hang out ‘cause you’re out of your mind",
  "And come hang out Don't you leave us behind",
  "And come hang out don’t you leave us behind But I’ll be there next time, I’ll be there next time",
  "And come hang out we can save you a shot But I’ll be there next time, I’ll be there next time",
  "And don't be afraid of the love that you had I won't let you down like the other boys did",
  "And for the wackos And the assholes",
  "And help us to find a home To search the Green and Town",
  "And I don't hate it, no And I don't hate it, no",
  "And I don't hate it, no I'm not famous, no",
  "And I don't hate it, no You've never heard of me",
  "And I feel like shouting, oh, I feel like shouting Oh, tonight, it don't matter who you're from",
  "And I told you that I need you baby Can't you see I'm alone oh oh?",
  "And I want to feel something again Won't you help me sober up",
  "And I want you to know I'm thinking of you",
  "And I want you to say You're thinking of me",
  "And I wonder, is something in the water make me wanting more? Make me wanting more",
  "And I'll hold you when you're lonely When you're cold cause you're the only girl for me",
  "And in my corduroy's we'd walk to school I sat and crossed my legs like Jim would do",
  "And it made me feel young And I want to feel something again",
  "And it's tough believing There's someone living out there",
  "And my jaw dropped down like the kick drum knew it",
  "And no thank you is how it should've gone I should stay strong",
  "And now after it all I just really wanna call my",
  "And now after it all, I just really wanna call My dad, my dad",
  "And now I'm shaking (shaking), waiting (waiting) As you come say hello (hello, hello, hello, hello)",
  "And now I'm walking in the rain I couldn't lie cause I was so afraid",
  "And now we celebrate If only for today",
  "And out of the jungle We could have been, we should have been",
  "And the river green Sometimes I wonder if we matter at all",
  "And then I wonder when we leave Will the moon still be white",
  "And we will grow without our parents Cause soon we will be giants too",
  "And we'll dance until we're dumb in the dark My lady, I know what you're thinking",
  "And we're dreaming of Bahamas So pass around the bottle",
  "And what can I do To get back to you",
  "And what's wrong with that But I'm weak",
  "And why should I spend time running for my life? And when the skies are open, we'll still be singing this",
  "Are you ready for tonight, setting it on fire And we'll dance until we're dumb in the dark",
  "As I walk you to your door (your door, your door, your door, your door) Now I'm feeling just like Woody Allen",
  "Baby tell me that you love me so Can you let me know",
  "Baby tell me you'll forgive me now Cause I don't know how I can let you down",
  "Baby, all the other boys - they don't see what I see Now, won't you say you see it in me?",
  "Baby, all the other boys they don't see what I see Now won't you say you see it in me?",
  "Baby, I will take you far away Don't you know these are our golden days?",
  "Be the kid for the win, singing Let the games begin",
  "Beauty lies, within the eyes Of the beholder, I'll be holding you close all night",
  "Before the giants learn from them Now we are the blessed",
  "Best thing about my life is I'm not famous, no Pa- paparazzi is at an all time low",
  "Boy it's good to know I got a bud like you Boy it's good to know",
  "Boy it's good to know I got a bud like you Enough, enough",
  "Boy it's good to know To pick me",
  "Boy, I bet I look so grown up Shirt tucked in my jeans",
  "Boy, oh boy I love it when I fall for that I'm weak, and what's wrong with that?",
  "Boy, oh boy I love it when I fall for that I'm weak",
  "Break me down, dirty jokes Watch me dear, and say what you wanna know (say what you wanna know)",
  "Break me down, I'm ready, break me down Break me down, I'm ready, break me down",
  "But at 7/11’s where you would find me Don’t wanna get paranoid",
  "But I could find some peace and privacy A paper company to sit with me",
  "But I give in so easily And no thank you is how it should've gone",
  "But I got so much I wanna say So I'm thinking rappers, they got it easy",
  "But I saw you smiling like dynamite in the record store And now I'm hoping (hoping), wishing (wishing)",
  "But I will never Find a one like you",
  "But I wouldn’t stop you I’m not narcissistic",
  "But I'm scared as hell That you won't like me in the morning",
  "But I'm so caught up in drama Everybody's talking",
  "But I'm up and I raise my cup and I wanna take her home I run my mouth",
  "But I'm weak, and what's wrong with that? Boy, oh boy I love it when I fall for that",
  "But I’ll be there next time, I’ll be there next time Come hang out ‘cause you’re missing a lot",
  "But I’ll be there next time, I’ll be there next time Last album’s sales could have been higher",
  "But it's just quiet Am I cruel?",
  "But please enjoy the show I didn’t smoke no grass today",
  "But she's heading home We're standing",
  "But soon we forget to smile At anything else",
  "But temptations of trouble on my tongue",
  "But that’s ‘cause I’m the one on stage So who am I to take away",
  "But that’s because I love to play So who am I to take away",
  "But this don't feel like Disney You say I turned out fine",
  "But tonight, call your friends down We're on our way now",
  "But we can make it rain It's thirsty thirsty thursday",
  "But we will live among the giants Before the giants learn to run",
  "But we're not too big to fail Now you're on top of the world tonight",
  "But what am I gonna do with mine? These things take time",
  "But when we cry, we cry together Like it was meant to be",
  "But who are we to wonder where we're going? Who am I to tell me who I am?",
  "But who I am is in these episodes So don't you tell me that it's just a show",
  "But-I'll be there next time I'll be there next ti-",
  "Cab ride, just up here on the right side Two more for the road",
  "Can we make it stop? Hold up, hold up But I'm so caught up in drama",
  "Can we skip to the good part? Ah",
  "Can you hold me close (Hold me close)",
  "Can you tell me when you're stoked to start? Are you ready for tonight, setting it on fire",
  "Cause I just need a Time and place to come through",
  "Cause I'm just a boy Who's telling a girl",
  "Cause I'm not famous, no Paparazzi is at an all time low",
  "Cause it makes me feel young Hello, hello",
  "Cause now, after it all, I'm just standing here to call My dad, my dad",
  "Cause she chose me to take her home I guess that's all I've ever wanted",
  "Cities pass like into stars And you're the one I'm looking for",
  "Come hang out ‘cause you’re missing a lot You haven’t gone that far you can find a real job",
  "Come hang out ‘cause you’re out of your mind You’re working so damn hard you forgot what you like",
  "Come out of the cold, we'll take the load And if they hurt you with words so cruel",
  "Could burn my heart away We are young",
  "Crew neck and a white blank check I'll be moving on my own",
  "Cross my heart and hope to die Since you came into my life",
  "Cuz I'm still turning out",
  "Dadadadad Dad dad dad",
  "Dadadadad Dadadad",
  "Damn, now all the pretty teens and fake IDs around me Where did they come from?",
  "Darlin', had enough And now I understand, so put your hands in mine",
  "Does the grass look greener On my side of the speakers",
  "Don't got a lot to say Girl on fire",
  "Don't leave me all on my own And so",
  "Don't leave my heart damaged I'll understand that things go a little bit better when you plan it",
  "Drove so fast my brain got buzzed And now I'm standin' here",
  "Enough, enough There's no celebrities here",
  "Every time I get the urge to go I'm the king of the island on a rusty throne",
  "Everybody's talking Everybody's talking now",
  "Everybody's talking now",
  "Everyone got their habits But you'll never hear what mine is",
  "Finally I'm right where I should be Like when you grow up doing donuts in the parking lot",
  "Forgot my retainer Could you not be mad at me?",
  "Girl on fire Could burn my heart away",
  "Good music's still good even if no one is watching Now you're on top of the world tonight",
  "Goodbye, goodbye I said to my bestest buds",
  "Got my attention it was all for you So don't take advantage",
  "Hang out 'cause you're outta your mind",
  "Happier than me Happier than me",
  "Hate it, hate-hate it (no) Hate it, hate- hate it",
  "Haters Where my haters",
  "Hello, hello I'm not where I'm supposed to be",
  "Hello, hello Last time that I saw your face",
  "Here we are again like we should've been Oh my lady can I have this dance?",
  "Here's some flowers 'Cause we're livin' on love",
  "Here's what we'll do, we'll all fight for you It's not your fault you don't feel safe",
  "Hey All our troubles gone",
  "Hey, and though I know it's been a long time in the records But I saw you smiling like dynamite in the record store",
  "Hey, Hey, Hey Tell me my love, you're ready to go?",
  "Hey! Hey! Now I'm feeling just like Woody Allen",
  "His label's doing the thing, and we were doing ours Champagne at the discotheque",
  "Hit some bars, and saw some bras And found a house to sleep",
  "Hold up, hold up But I'm so caught up in drama",
  "Hold up, hold up Can we make it stop",
  "How's it go again? My favorite color is you",
  "How's it go again?",
  "I been out walking By the shore",
  "I can’t complain, no I won’t be mourning Cause I skipped on prom for Elvis Duran in the Morning",
  "I could do But I'm confused",
  "I could really use a bud like you To pick me",
  "I didn't know her, couldn't hold her Bones didn't settle in",
  "I didn't smoke no grass today But that’s ‘cause I’m the one on stage",
  "I didn’t smoke no grass today But that’s because I love to play",
  "I don't got 'em, I'm not famous, no It's don't matter what my name is",
  "I don't got one, I'm not famous, no And I don't hate it, no",
  "I don't need nothing else but you I don't wanna fall in love over subtweets",
  "I don't need nothing else but you Right vibe right come and vibe with me tonight",
  "I don't need nothing else but you Sometimes I wonder why I fool with you",
  "I feel so broke up, I wanna go home No, I feel so broke up, I wanna go home",
  "I found you Darlin', I found you (oh)",
  "I had my first crush in season 2 She passed me notes and filled our hands with glue",
  "I hold you I hold you closer than I ever knew",
  "I hope it's not far 'cause I thought it'd be today",
  "I hope she holds on to what I told her The boys around her take a second look",
  "I hope that you're missing me 'Cause it makes me feel young",
  "I just can't believe That you chose a guy like me",
  "I just really wanna call my da- And what's wrong with that",
  "I just want to feel something again How's it go again?",
  "I keep doing me Don’t wanna get paranoid",
  "I know they're coming for me, we're not the pitchfork kids Ooh, ooh, it's the loneliest life that we live",
  "I know what you're thinking When the bass starts ringing",
  "I know you'll like me the way that I like you",
  "I lost my grandmother in season six I watched my mom, she cried and held her kids",
  "I napped on campus and I smoked at dances but",
  "I promise I won't budge One sip, bad for me",
  "I put my heart, I put my soul, I put my life in it Look at me now",
  "I run my mouth Don't got a lot to say",
  "I should stay strong But I'm weak, and what's wrong with that?",
  "I think I'm still turning out I hope you stick around",
  "I think I'm still turning out I think I'm still turning out",
  "I think I'm still turning out You say I turned out fine",
  "I thought I had the ADHD But that's a real thing and I'm just lazy",
  "I thought I'd recognize when love was true But I'm confused",
  "I thought I’d get clever Make my lyrics come out better",
  "I throw my fingers to the ceiling and I won't give in Look at me now",
  "I tried a couple weekends But that green’s not for me",
  "I turned down Jameson when I was 12 I spent that Friday night with Steve Carell",
  "I walked on sippin' on on that love",
  "I was feeling kind of alone 'till I heard that track Go!",
  "I was lost in my feet On an empty street",
  "I was so young to leave you all alone And I want you to know",
  "I will go down that road The one that takes you home",
  "I will search the green And I will search the town",
  "I woke up last night from a dream That we'd grow old on Bleecker Street",
  "I won't forget you, but I may Forget your name",
  "I'll be there next time But-I'll be there next time",
  "I'll be there next time I'll be there next time",
  "I'll just keep doing me Haters",
  "I'll send a postcard from the sky My calling, my calling",
  "I'll take my time I'll take my time",
  "I'm a little kid with so much doubt Do you want to be there to see how I turn out?",
  "I'm a little kid, and so are you Don't you go and grow up before I do",
  "I'm better off without you, 'cause the man ain't me! (My oh my) I'm going right now",
  "I'm coming up, it might be my calling, my calling I'm coming up, it might be my time",
  "I'm coming up, it might be my time I'm taking off, you might say I'm all in, I'm all in",
  "I'm gonna be a people person in a room of people-people Imma keep on running this shit",
  "I'm just a boy who's telling a girl That when I grow up I'll buy you a rose",
  "I'm not famous, no And I don't hate it, no",
  "I'm not famous, no I'm not famous, no",
  "I'm not famous, no",
  "I'm not important yet If you put this scene on a movie screen",
  "I'm not one to take it fast I got the best seat back in history class",
  "I'm not where I'm supposed to be I hope that you're missing me",
  "I'm ready… Break me down, I'm ready, break me down",
  "I'm sailing by the clouds above her I'm finding out what all this means",
  "I'm taking off, you might say I'm all in, I'm all in I'll send a postcard from the sky",
  "I'm thinking of you All the pretty girls they find",
  "I'm weak Go!",
  "I'm weak, and what's wrong with that? Boy, oh boy I love it when I fall for that",
  "I've seen almost every side of the industry Except the side we've been working seven years to see",
  "I’ll be there next time, I’ll be there next time I’ll be there next time, I’ll be there next time",
  "I’m just high off the music And I don’t wanna miss it",
  "If cloudy skies should take our friends And we will learn form the giants",
  "If Ed Sheeran writes my song I'll finally top the charts",
  "If he's just pressing play Kickin' in the basement",
  "If I ever started rapping They'd be laughing, they won't believe me",
  "If I need a pick me up Would you come and pick me up?",
  "If we're not written down Who will remember now?",
  "Imma be the kid for the win Let the games begin",
  "Imma keep on running this shit Let the games begin",
  "In a big white house, in a big white bed Darling, this is not the end",
  "In my mind I thought the birds would sing and sparks would fly",
  "Is it called the happy end? If the word gets me where I'm supposed to be",
  "It didn't feel so great If you put this scene on a movie screen",
  "It don't matter what my name is I don't got one, I'm not famous, no",
  "It's another bumpy road But I'm up and I raise my cup and I wanna take her home",
  "It's bullshit and we know it Like a flower sheltered in stone",
  "It's cool you feel the same Like why's the DJ here?",
  "It's don't matter where my name is I don't got one, I'm not famous, no",
  "It's not your fault you don't feel safe It's not your fault so don't take blame",
  "It's on us Know that it's on us",
  "It's on us Though your trust is stolen",
  "It's so wrong I didn't know until you were gone",
  "It's thirsty thirsty thursday (yodeling)",
  "John's too big to fail Make it superstar",
  "Just give me the vibe to Slide on I might make you mine by tonight",
  "Just some kids with pro tools, and a mic, and a big idea (But no IDs)",
  "Just wanna be making noise You want a hit, it’s your choice",
  "Keep doing keep doing me Whoa-oo-ah",
  "Keep on running this shit Be the kid for the win, singing",
  "Keep- keep doing keep doing me Keep doing keep doing me",
  "Kickin' in the basement Hatin' all the same things too",
  "Know that it's on us I wonder where, where your mind goes",
  "La La La (Keep on bouncin') La La La (Like no one's watching)",
  "La La La La La La",
  "La La La(We so thirsty) La La La(Can't no one stop me)",
  "Last round for A.M. lovers That's how I come alive",
  "Last time that I saw your face Was recess in second grade",
  "Laughing the disco ball Like who'd invest in that?",
  "Left without nothing but our bags to hold on to Yeah out in the daylight",
  "Let the games begin (GO!) Let the games begin",
  "Let the games begin A people person in a room of people-people",
  "Let the games begin Keep on running this shit",
  "Let the games begin Let the fun begin",
  "Let the games begin Let the games begin",
  "Let's drink to everything we got Let's dance for everything we're not",
  "Let's take it back and take in every moment Who am I to tell me who I am?",
  "Like I'm out on your doorstep We could have been, we should have been",
  "Like when we were young Take me back to where we all began",
  "Like when you grow up doing donuts in the parking lot You hit the station go insane and when the kick-drum drops",
  "Listen to my aching heart Quick, before you skip the song",
  "Listen to my aching heart Will you keep this record on",
  "Make it right together We can fight together",
  "Make love to the rumours instead Maybe we're addicted to it all",
  "Make me wanting more A heartbreak and a hundred red balloons, now I'm off the floor",
  "Make our way through rusty towns Lift the weight up off your back",
  "Maybe I'm stuck on what I see on TV I grew up on Disney",
  "Maybe that’s why I haven’t seen friends in a while They’re at a bar down in the Bahamas",
  "Met so many faces that Will probably forget me",
  "Mom and dad, they have a good life But what the hell am I gonna do with mine?",
  "My calling, my calling And I wonder, is something in the water make me wanting more?",
  "My calling, my calling Oh, Cleopatra was a lover But this world of mine is turning green",
  "My lady, I know what you're thinking When the bass starts ringing",
  "My mind was broken up I couldn't think So I just hugged her the way Michael did",
  "My momma says to pick the best And you are it",
  "Never spoken with my mouth full Yeah that's a mouthful and I'm doubtful",
  "No matter where you go I will go down that road",
  "No one should know if you bleed red or blue You just bleed you, and I'll sit with you",
  "No point in crying without that someone there beside you Saying it will be okay",
  "No point in dreaming if you’re alone No point in walking without the road",
  "No story's a fairytale I don't know if we'll make it",
  "No thank you is what I should've said I should be in bed",
  "No, I feel so broke up, I wanna go home No, I feel so broke up, I wanna go home",
  "Nobody knows my quirks 'Cause I'm not famous, no",
  "Nobody knows what you're going through So you just be you, and I'll be that, too",
  "Now I'm feeling just like Woody Allen Finally I'm right where I should be",
  "Now the finale's done and I'm alone I'm on a netflix trip here on my phone",
  "Now we are the blessed Now we are the strong",
  "Now we are the strong Take my hand, and let me know",
  "Now we're livin' on love (Livin' on love, livin' on love, livin' on love Livin' on love, livin' on love, livin' on love)",
  "Now we're livin' on love Hey, you're the one I wait for",
  "Now you can't go breaking my heart (h-heart h-heart) Now you can't go breaking my heart, ooh",
  "Now you can't go breaking my heart (My oh my) I'm going back now",
  "Now you can't go breaking my heart Feel like I need, to forget you",
  "Now you found some other man, you see I'm better off without you, 'cause the man ain't...",
  "Oh father, father, I'm a dreamer We dream of green, but now we're gray",
  "Oh my God, what's going on? This night got fuckin' weird",
  "Oh my lady can I have this dance? My lady",
  "Oh we'll never look like all the models in the movies We'll never know",
  "Oh-oh-oh And when the weekend comes around",
  "Oh-oh-oh Called you up so we could reminisce",
  "Oh-oh-oh Oh-oh-oh",
  "Oh-oh-oh",
  "Oh—(hey), oh—(hey), oh— Now we're livin' on love",
  "Oh, I didn’t smoke no grass today But that’s ‘cause I’m the one on stage",
  "Oh, ohhh Now you're on top of the world tonight",
  "Oh, tambourines and skinny jeans Oh, won't you be my summer love",
  "One hit, bad for me One kiss, bad for me",
  "One kiss, bad for me But I give in so easily",
  "One sip, bad for me One hit, bad for me",
  "One us sippin' on that fun It's a feeling we ain't told",
  "Ooh waaaaaaa ee ya ee yaaaaa",
  "Ooh, ooh, she's the rough and the rowdiest kid Ooh, ooh, and there's more where she lives",
  "Ooh, ooh, we're not running with the pitchfork kids The moon is upon us, gaining on us",
  "Or am I ignorant or was I fooled By the stories I knew",
  "Or the weird shit I do and say That's my favorite thing",
  "Pa- paparazzi, they don't care where I go Where my haters, where my haters?",
  "Paparazzi, they don't care where I go Where my haters, where my haters",
  "Passed out, all my friends went and passed out So much for the night",
  "Perfume and a hotel room We go bouncin' back for more",
  "Probably because reality blows When did all my friends become so loud?",
  "Recently he said that she said that we said that he said some shit about me",
  "Recently he said, that she said, that we said some shit that you wouldn't believe",
  "Remember alcohol and dancing Our friends are gone now",
  "Run away girl, 'cause I let you Now you found some other man, you see",
  "Sayin' you You make me feel so brand new",
  "Send me your location Let's find the vibrations",
  "Send me your location Let's focus on communicating",
  "She made a choice the night is over I just can't believe",
  "She moved away I was on season 3 It hit my heart so hard I'd hardly speak",
  "She's crossed there, to stay",
  "She's gotta have it, gotta have it Oh with her hipster friends",
  "Should I go for more clicks this year (And what's wrong with that) Or should I follow the click in my ear",
  "Should I go for more clicks this year But I'm weak (Should I go for more clicks th-)",
  "Should I go for more clicks this year Or should I follow the click in my ear (But I'm weak)",
  "Should I go for more clicks this year Or should I follow the click in my ear (See you next time)",
  "Should I go for more clicks this year Or should I follow the click in my ear",
  "Should I go for more clicks this year Or should I follow the-",
  "Should there be a difference Do you have instructions",
  "Sit by the fire and I'd play my guitar But dreams are only dreams",
  "So bar scenes weren't an option Ukulele DJs, only band in the genre",
  "So can we skip to the good part? Ah",
  "So here I go I'm coming up, it might be my calling, my calling",
  "So how am I supposed to fit this In three minutes and thirty seconds",
  "So I said you seemed infinity You forever figures 5 and 3",
  "So I'll be there, it's not on you (It's on us, it's on us)",
  "So if no one's paying attention Then does my voice get to your headphones",
  "So let's get personal I gotta lot of cool spots that we can go",
  "So send me your location Let's focus on communicating",
  "So we're caught up in drama (Everybody's talking, Everybody's talking)",
  "So who am I to take away What makes you feel this great",
  "So why's the bouncer taking everything so seriously? It's you and I",
  "So won't you send me your location Let's focus on communicating",
  "Someone told me to be selfless But we are helpless without attention",
  "Sometimes when that game hits the wrong vibe You take it home",
  "Stick a needle in my eye My momma says to pick the best",
  "Still that green’s not for me On corners people cursing",
  "Stroll the westside after dark You are shining, you're an angel",
  "Take in every moment Hold it close again",
  "Take me back to where we all began Here we are again like we should've been",
  "Take me back to where we all began Take you dancing in the park",
  "Take my hand, and let me know That it feels good",
  "Take you walking through the garden Take my heart when summer comes",
  "Tell me my love, you're ready to go Don't leave me all on my own",
  "Tell me that you're ready and you're feeling the vibe Someday I'll be so damn sublime",
  "Tell me what's the move and I got you I'm only acting like this 'cause I like you",
  "That I could get these lyrics out, oh Cause I think fast but I sing slow",
  "That I'm not famous, no And I'm never on TV",
  "That it feels good To feel at home",
  "That rhythm all around us Sweet love, it finally found us",
  "That when I grow up I'll buy you a rose When I grow up I'll buy you a rose",
  "That you chose a guy like me No matter where you go",
  "That you won't like me in the morning That you won't like me the way that I like you",
  "That you won't like me the way that I like you And all is well",
  "The air was still And still the water cold",
  "The audience it flickers They’re lighting up like Christmas",
  "The coldest traincar 3 o'clock at dawn",
  "The coldest traincar Chilly friday night",
  "The drama is dangerous But its so exciting to us",
  "The one by the river in summer I'll keep you safe",
  "The one that takes you home After the party's done",
  "The one where Dwight became the head of sales My eighth grade graduation wished me well",
  "The way to keep you on my mind I swear I heard you singing along",
  "The world is a marble heart; Too fragile, too broken",
  "There's a long day ahead She is lost in her bed",
  "There's no one here that we know I think I knew a girl who knew the host",
  "These things take time Mom and dad, they have a good life",
  "They call me after dark, I don't want no part My habits, they hold me like a grudge",
  "They started fighting with my friend And I can't find him now",
  "Thirsty thirsty Thursday (yodeling)",
  "Thirsty thirsty thursday I'm up and I raise my cup see 'em bouncin' on the floor",
  "Thirsty thirsty thursday I'm up and I raise my cup singing everything is gold",
  "Thirsty thirsty thursday Thirsty thirsty thursday",
  "Thirsty thirsty thursday",
  "This kind of chill It helps me cope",
  "Though your heart is broken You are never broken",
  "Though your trust is stolen Though your heart is broken",
  "Three cheers for what we didn't say Well, if it matters",
  "Throwing up on an LA street Nobody judges me",
  "To feel at home We would sail across the ocean",
  "To feel at home What can I say",
  "To get back to you And help us to find a home",
  "To legalize their burning But that ain’t no concern of mine",
  "To search the Green and Town A year from now",
  "Tonight we're 21 under all these lights (Hey)",
  "Troubles yet to come One sip, bad for me",
  "Tryna stick it to the man before we’re grown And through that struggle, we made a star",
  "Up on a hill, down by the river That river took my girl away",
  "Wait each and every day for You (you!), you (you!), baby",
  "Wait, give me a minute, just a minute, get my focus straight They're looking bored",
  "Was it all in my head? In an empty bed",
  "Was it hard to believe? Wear your heart on my sleeve",
  "Was looking forward to Being important but",
  "Was recess in second grade And it made me feel young",
  "Wasted, wasted love You had so much to give for giving every time",
  "Watch you playing and playing and playing these guys Catch my stare, little smile",
  "Watching clouds overhead Here she lies in her bed",
  "Way up to the moon Boy it's good to know I got a bud like you",
  "Way up, way up Way up to the sky",
  "We are human after all And we don't stay for long",
  "We are young But we can make it rain",
  "We can fight together It's on us",
  "We can try together Make it right together",
  "We had to part, couldn't break her heart 'cause their blood pumps through her veins",
  "We may be lost, and gone forever The rain will wash our memory",
  "We said that we'd keep in touch And we did our best",
  "We traded our boring lives For MTV story lines",
  "We went dancing on the roof And took some girls uptown",
  "We won't be lovers We'll just be suits and ties and shoes",
  "We, we fall for that Can't wait to fall again",
  "We, we fall for that Wake up, we fall again",
  "We'll arrive behind a hashtag sign I won't forget you, but I may",
  "We'll be found in Frankie's town And tell the world we're gonna shake the ground",
  "We're caught up in problems (Everybody's talking, Everybody's talking)",
  "We're gonna figure it out Who can I turn to now?",
  "We've got a way to go And what can I do",
  "Wealthy people learned their lesson And never donate without the press there",
  "Well this is new to me, this is new to you Initially I didn't wanna fall for you",
  "What can I do? Let's toast the ones who got away",
  "What can I say Without a say?",
  "What makes you feel this great I didn’t smoke no grass today",
  "What makes you feel this great I’m not narcissistic",
  "What makes you feel this great Last night at the concert",
  "What your heart couldn't handle Feel like I need, to forget you",
  "When did all my friends become so loud? We act like reality shows",
  "When did all my friends turn into fake IDs and skinny jeans? I don't belong",
  "When did my friends get so loud? When did my friends get so loud?",
  "When did our problems get so small? We break up with lovers and friends",
  "When everybody here is sneaking in and getting high Way up, way up",
  "When I'm still turning out When I'm still turning out",
  "When no one's looking at it Kickin' in the basement",
  "When the bass starts ringing Can you tell me when you're stoked to start?",
  "When these words are set on a paper You will never be a stranger now",
  "Where my haters Think I'm still turning out",
  "Where my haters, where my haters? I don't got 'em, I'm not famous, no",
  "While I’m doing promo, trying to blow up in Chicago Yep yep I’m gonna miss this someday",
  "Who am I to tell me who I am? Who am I to tell me who I am?",
  "Who are we to wonder where we're going? Who am I to tell me who I am?",
  "Who the fuck wants to rule, ruling all alone, alone, alone, alone Hey and though I know it's been a long time in the records",
  "Whoa-oo-ah (No grass today)",
  "Whoa-oo-ah (No-no grass today)",
  "Whoa-oo-ah Whoa-oo-ah",
  "Why? Recently he said, that she said, that we said some shit that you wouldn't believe",
  "Will I be here next year or Are these my best years yet?",
  "Will I know I've made it then? It's so hard",
  "With no chance of re-growing Like push comes to shove",
  "With only my soul left Feel like I need,(woah) to forget you",
  "Without a say? We've got a way to go",
  "Won't you help me feel something again Can I finally feel something again",
  "Won't you help me feel something again Haters",
  "Won't you help me feel something again How's it go again?",
  "Won't you help me sober up Growing up it made me numb",
  "Wonder where we're going Tell me who I am",
  "Yeah when I grow up I'll buy you a rose",
  "Yep yep I missed another Friday And all my friends say",
  "Yep yep I’m gonna miss this someday Yep yep I missed another Friday",
  "You are never broken It's on us",
  "You can do anything you want And we're just children in a world of diversion",
  "You can do anything you'd like And through that struggle, we made a star",
  "You cannot rush What can’t be timed",
  "You haven’t gone that far you can find a real job (find a real job)",
  "You hit the station go insane and when the kick-drum drops You know now I'm feeling just like Woody Allen",
  "You just keep doing you (You just keep doing you like)",
  "You keep me young and that's how I wanna be Hello, hello",
  "You keep me young and that's how I wanna be My favorite color is you",
  "You know now I'm feeling just like Woody Allen Oh-oh-oh",
  "You know oh oh Cross my heart and hope to die",
  "You light up if you like it And though I may not like it",
  "You never overheard That I blew twenty grand on shirts",
  "You start thinking about the clock ticks You get nervous, you start stressing",
  "You wanna skip it if it's wordy But fit the whole song in three-thirty",
  "You're vibrating out my frequency My favorite color is you",
  "You're with me love, just relax Now I'm feeling just like Woody Allen",
  "You're working so damn hard You forgot what you like",
  "You’re working so damn hard you forgot what you like And come hang out don’t you leave us behind",
  "(Boy, oh boy I love it when I fall for that) No thank you",];

post();
setInterval(post, 1000*60*60);

//post();
//setInterval(post, 1000*60);

function post(){
  var i = getRandomIndex();
  var one = quotes[i];
  var tweet = {
    status: one
  }
  T.post('statuses/update', tweet, tweeted);
  function tweeted(err, data, response){
    if(err){
      console.log("Something went wrong!");
    }else{
      console.log("Tweet posted!");
      console.log(i + ": " + one);
    }
  }
}

function getRandomIndex(){
  return (Math.floor(Math.random() * quotes.length))
}
